// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice = ListsSlice | HeroSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *Settings → NavBar*
 */
export interface SettingsDocumentDataNavbarItem {
  /**
   * Name field in *Settings → NavBar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navbar[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Link field in *Settings → NavBar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navbar[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Settings → Contact Info*
 */
export interface SettingsDocumentDataContactInfoItem {
  /**
   * Info Type field in *Settings → Contact Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_info[].info_type
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info_type: prismic.KeyTextField;

  /**
   * Info field in *Settings → Contact Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_info[].info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_name: prismic.KeyTextField;

  /**
   * Site Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  site_logo: prismic.ImageField<never>;

  /**
   * Site Address field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_address: prismic.KeyTextField;

  /**
   * NavBar field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navbar[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navbar: prismic.GroupField<Simplify<SettingsDocumentDataNavbarItem>>;

  /**
   * Header Color field in *Settings*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.header_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  header_color: prismic.ColorField;

  /**
   * NavBar Color field in *Settings*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navbar_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  navbar_color: prismic.ColorField;

  /**
   * Contact Info field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_info[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contact_info: prismic.GroupField<
    Simplify<SettingsDocumentDataContactInfoItem>
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = HomeDocument | SettingsDocument;

/**
 * Item in *Hero → Default → Primary → Carousel*
 */
export interface HeroSliceDefaultPrimaryCarouselItem {
  /**
   * Banner Title field in *Hero → Default → Primary → Carousel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.carousel[].banner_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  banner_title: prismic.KeyTextField;

  /**
   * Banner Subtitle field in *Hero → Default → Primary → Carousel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional
   * - **API ID Path**: hero.default.primary.carousel[].banner_subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  banner_subtitle: prismic.KeyTextField;

  /**
   * Banner Image field in *Hero → Default → Primary → Carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.carousel[].banner_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner_image: prismic.ImageField<never>;

  /**
   * Link to Product field in *Hero → Default → Primary → Carousel*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Optional
   * - **API ID Path**: hero.default.primary.carousel[].link_to_product
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_to_product: prismic.LinkField;

  /**
   * Banner Type field in *Hero → Default → Primary → Carousel*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Type 1 (image to the right)
   * - **API ID Path**: hero.default.primary.carousel[].banner_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  banner_type: prismic.SelectField<
    "Type 1 (image to the right)" | "Type 2 (image to the left)",
    "filled"
  >;

  /**
   * Banner Color field in *Hero → Default → Primary → Carousel*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.carousel[].banner_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  banner_color: prismic.ColorField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Carousel field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryCarouselItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Lists → Default → Primary*
 */
export interface ListsSliceDefaultPrimary {
  /**
   * Title field in *Lists → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lists.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Filter field in *Lists → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: lists.default.primary.filter
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  filter: prismic.SelectField<
    | "None"
    | "Ofertas"
    | "VejaTambem"
    | "VocePodeGostar"
    | "VistosRecentemente"
    | "OutrosProdutos"
    | "ProdutosSimilares",
    "filled"
  >;

  /**
   * Color field in *Lists → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: lists.default.primary.color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  color: prismic.ColorField;
}

/**
 * Default variation for Lists Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ListsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Lists*
 */
type ListsSliceVariation = ListsSliceDefault;

/**
 * Lists Shared Slice
 *
 * - **API ID**: `lists`
 * - **Description**: Lists
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListsSlice = prismic.SharedSlice<"lists", ListsSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavbarItem,
      SettingsDocumentDataContactInfoItem,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimaryCarouselItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ListsSlice,
      ListsSliceDefaultPrimary,
      ListsSliceVariation,
      ListsSliceDefault,
    };
  }
}
